services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./admin
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    restart: always
    volumes:
      - ./admin:/app
      - /app/node_modules
      - /app/.next

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
