version: "3"
services:
  backend:
    build: ./server
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb+srv://Emmanuelle:Emmanuelle@cluster0.ajjdzwm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  frontend:
    build: ./admin
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    develop:
      watch:
        - action: sync
          path: ./admin
          target: /app
          ignore:
            - node_modules/

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
